services:
  - type: web
    name: wa-bot-faiz
    env: node
    buildCommand: npm install --production
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: Asia/Jakarta
